[package]
name = "hungry-test"
edition = "2024"

[dependencies]
hungry = { path = "../../lib/hungry" }
tokio = { version = "1.48.0", features = ["rt", "net", "signal"] }
anyhow = "1.0.99"
bytes = "1.10.1"
rand = "0.9.2"
hex = "0.4.3"
